site_name: ShivaOps DevOps Lab
site_url: https://shivaops.github.io/shivaops-devops-lab/
repo_url: https://github.com/shivaops/shivaops-devops-lab
repo_name: GitHub
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Kubernetes Setup: kubernetes-setup.md
  - CI/CD Pipeline: ci-cd.md
  - Application Deployment: app-deployment.md
  - Architecture & Networking: architecture.md
